### ISSUE TITLE
Image feature extraction details and errors in running

### ISSUE THREAD

**Issue by Verathagnus** [DeepLearnXMU/MNMT#2]
Could you please give details about how the image features were extracted? According to the multi 30k dataset repo that was mentioned in the research paper, we found pre-extracted images features in .npy format but the repo needs .hdf5 format for the image features and showed an error regarding that. So we used the [https://github.com/iacercalixto/MultimodalNMT](https://github.com/iacercalixto/MultimodalNMT) repo to generate them manually. But we aren't sure if it works as we couldn't proceed due to another issue as given below for en-de pair.

```
start  interate 860694166998602247
starting epoch 1
Loading train dataset from data.train.1.pt, number of examples: 29000
Traceback (most recent call last):
  File "train.py", line 595, in <module>
    main()
  File "train.py", line 586, in main
    valid_img_feats=valid_img_feats)
  File "train.py", line 290, in train_model
    train_stats = trainer.train(train_iter, epoch, report_func)
  File "/home/cnlp/Intern_multimodalNMT/MNMT/onmt/Trainer.py", line 201, in train
    report_stats, normalization)
  File "/home/cnlp/Intern_multimodalNMT/MNMT/onmt/Trainer.py", line 368, in _gradient_accumulation
    self.model(src, tgt, src_lengths, dec_state, img_feats)
  File "/home/cnlp/miniconda3/envs/semantic_mnmt/lib/python3.6/site-packages/torch/nn/modules/module.py", line 489, in _call_
    result = self.forward(*input, **kwargs)
  File "/home/cnlp/Intern_multimodalNMT/MNMT/onmt/Models.py", line 737, in forward
    context_img=img_proj)
  File "/home/cnlp/miniconda3/envs/semantic_mnmt/lib/python3.6/site-packages/torch/nn/modules/module.py", line 489, in _call_
    result = self.forward(*input, **kwargs)
  File "/home/cnlp/Intern_multimodalNMT/MNMT/onmt/Models.py", line 365, in forward
    img_text_alignment= self.bi_attn_text_guiding_img( context_img.contiguous(),memory_bank,memory_lengths)       #[batch, img_feat_num, src_len]  还没有softmax完的
  File "/home/cnlp/miniconda3/envs/semantic_mnmt/lib/python3.6/site-packages/torch/nn/modules/module.py", line 489, in _call_
    result = self.forward(*input, **kwargs)
  File "/home/cnlp/Intern_multimodalNMT/MNMT/onmt/modules/GlobalAttention.py", line 174, in forward
    aeq(batch, batch_)
  File "/home/cnlp/Intern_multimodalNMT/MNMT/onmt/Utils.py", line 11, in aeq
    "Not all arguments have the same value: " + str(args)
AssertionError: Not all arguments have the same value: (16, 4)
Closing remaining open files:flickr30k_train_vgg19_bn_cnn_features.hdf5...doneflickr30k_valid_vgg19_bn_cnn_features.hdf5...done
```
We used the files from both raw text and tokenized text folders in multi 30k dataset, but we still get the error.
We printed the memory_bank.size() and input.size() and found that they became different as given.
```
4 4 256
1 196 256
```
Also, if we set batch size = 1, we get the following error:
```
* number of parameters: 6351637
encoder:  1348096
decoder:  5003541
Making optimizer for training.

Start training...
 * number of epochs: 10, starting from Epoch 1
 * batch size: 1
start  interate 8643075770505484670
starting epoch 1
Loading train dataset from data.train.1.pt, number of examples: 28927
Traceback (most recent call last):
  File "train.py", line 595, in <module>
    main()
  File "train.py", line 586, in main
    valid_img_feats=valid_img_feats)
  File "train.py", line 290, in train_model
    train_stats = trainer.train(train_iter, epoch, report_func)
  File "/home/cnlp/Intern_multimodalNMT/MNMT/onmt/Trainer.py", line 201, in train
    report_stats, normalization)
  File "/home/cnlp/Intern_multimodalNMT/MNMT/onmt/Trainer.py", line 368, in _gradient_accumulation
    self.model(src, tgt, src_lengths, dec_state, img_feats)
  File "/home/cnlp/miniconda3/envs/semantic_mnmt/lib/python3.6/site-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/cnlp/Intern_multimodalNMT/MNMT/onmt/Models.py", line 726, in forward
    img_proj = self.encoder_img( context_img )
  File "/home/cnlp/miniconda3/envs/semantic_mnmt/lib/python3.6/site-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/cnlp/Intern_multimodalNMT/MNMT/onmt/Models.py", line 851, in forward
    out = self.layers(input)
  File "/home/cnlp/miniconda3/envs/semantic_mnmt/lib/python3.6/site-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/cnlp/miniconda3/envs/semantic_mnmt/lib/python3.6/site-packages/torch/nn/modules/container.py", line 92, in forward
    input = module(input)
  File "/home/cnlp/miniconda3/envs/semantic_mnmt/lib/python3.6/site-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/cnlp/Intern_multimodalNMT/MNMT/onmt/Models.py", line 922, in forward
    return input.view(*self.shape)
RuntimeError: shape '[-1, 196, 512]' is invalid for input of size 25088
Closing remaining open files:flickr30k_train_vgg19_bn_cnn_features.hdf5...doneflickr30k_valid_vgg19_bn_cnn_features.hdf5...done
```
We used the following code to run:
```
!python train.py \
    -data data \
    -save_model model \
    -optim adam \
    -learning_rate 0.003 \
    -use_nonlinear_projection \
    -path_to_train_img_feats flickr30k_train_vgg19_bn_cnn_features.hdf5 \
    -path_to_valid_img_feats flickr30k_valid_vgg19_bn_cnn_features.hdf5 \
    -image_feat_type local \
    -encoder_type brnn \
    -enc_layers 1 \
    -dec_layers 1 \
    -global_attention mlp \
    -rnn_type GRU \
    -dropout 0.3 \
    -bi_attention 1 \
    -co_attention 1 \
    -epochs 10 \
    -batch_size 1 \
    -language en_de \
    -gpuid 0
```
We did try commenting the aeq calls in the [https://github.com/DeepLearnXMU/MNMT/blob/master/onmt/modules/GlobalAttention.py](https://github.com/DeepLearnXMU/MNMT/blob/master/onmt/modules/GlobalAttention.py) files but due to different batch sizes, it couldn't start training.

**Comment by lighter47** [comment]
Sorry for the late reply. I think you can try to change the dimension to 512 in onmt/ModelConstructor.py (Line 274).
The current version lacks generality and some configurations are hard-coded, so please feel free to contact me (hjiang@stu.xmu.edu.cn) for any questions about our paper.

**Comment by Verathagnus** [comment]
Got it. Thanks for the reply. I'll do that.
